config/routes.rb
Rails.application.routes.draw do
  root 'usuarios#login'
  resources :hosts
  resources :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/host.rb
class Host < ApplicationRecord
  belongs_to :usuario_id
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def host_params
      params.require(:host).permit(:nome, :endereco, :usuario_id_id)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login
    if session["usuario"].nil? 
      @usuario = Usuario.new
    else 
      redirect_to controller: "hosts", action: "index"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:login, :senha, :email)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/hosts/_form.html.erb
<%= form_with(model: host) do |form| %>
  <% if host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
        <% host.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :usuario_id_id %>
    <%= form.text_field :usuario_id_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing Host</h1>

<%= render 'form', host: @host %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hosts</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hosts.each do |host| %>
      <tr>
        <td><%= host.nome %></td>
        <td><%= host.endereco %></td>
        <td><%= host.usuario_id_id %></td>
        <td><%= link_to 'Show', host %></td>
        <td><%= link_to 'Edit', edit_host_path(host) %></td>
        <td><%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host', new_host_path %>

app/views/hosts/new.html.erb
<h1>New Host</h1>

<%= render 'form', host: @host %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @host.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @host.endereco %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @host.usuario_id_id %>
</p>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pingador</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Senha</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.login %></td>
        <td><%= usuario.senha %></td>
        <td><%= usuario.email %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/login.html.erb
<%= form_with(model: @usuario) do |form| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= Login ou senha inválidos %></h2>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha %>
  </div>

  <div class="actions">
    <%= form.submit value="Login" %>
  </div>
<% end %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @usuario.login %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @usuario.senha %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>